language: java
jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - (cd src/main/docker && exec docker-compose up -d)
  - docker ps

install: mvn install -P docker

after_script:
  - (cd src/main/docker && exec docker-compose down)