language: java
jdk:
  - oraclejdk8

services:
  - docker

install: mvn install -P docker

before_script:
  - (cd src/main/docker && exec docker-compose up -d)
  - docker ps
  - sleep 30

script: mvn test -Pintegration-test

after_script:
  - (cd src/main/docker && exec docker-compose down)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mkhackathon/graphhopper
  - docker push mkhackathon/redways

