geocoder:
  email: ${OSM_EMAIL:louis@test.co.uk}
  google:
    apiKey: ${GOOGLE_API_KEY}

graphhopper:
  routingUrl: http://localhost:8989/route

server:
  port: ${SERVER_PORT:8443}
  ssl:
    key-store: ${SSL_CERT_LOCATION:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:123456}
    keyStoreType: ${SSL_KEYSTORE_TYPE:PKCS12}
    keyAlias: ${SSL_KEY_ALIAS:tomcat}

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

