geocoder:
  email: ${OSM_EMAIL:louis@test.co.uk}
  google:
    apiKey: ${GOOGLE_API_KEY:x}

graphhopper:
  routingUrl: ${GRAPHHOPPER_URL:http://localhost:8989/route}

server:
  port: ${SERVER_PORT:8080}

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

