version: '2'
services:
  redways:
    image: "mkhackathon/redways"
    hostname: redways
    links:
        - graphhopper:graphhopper
    environment:
      GRAPHHOPPER_URL: "http://graphhopper:8989/route"
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
     - 8443:8443

  graphhopper:
    image: "mkhackathon/graphhopper"
    hostname: graphhopper
    ports:
      - 8989:8989